name=ESPfuscate
version=1.0.0
author=AndreaDV
maintainer=AndreaDV
sentence=Hardware-bound string encryption for ESP32.
paragraph=CompileTime and RunTime plain text obfuscation for all ESP32 families.
category=Security
url=https://github.com/AndreaDV01/ESPfuscate
architectures=esp32