name=ESPfuscate
version=0.2.0
author=AndreaDV01
maintainer=AndreaDV01
sentence=Hardware-bound string encryption for ESP32.
paragraph=CompileTime and RunTime plain text obfuscation for all ESP32 families.
category=Security
url=https://github.com/AndreaDV01/ESPfuscate
architectures=esp32