name=ESPfuscate
version=0.4.3
author=AndreaDV01
maintainer=AndreaDV01
sentence=ESP32 Sensitive Data Obfuscator
paragraph=Lightweight ESP32 security library with compile-time obfuscation and runtime encryption.
category=Other
url=https://github.com/AndreaDV01/ESPfuscate
architectures=esp32